### ISSUE TITLE
when run the restore hub cluster backup showing  error

### ISSUE THREAD

**Issue by irshadstars** [stolostron/cluster-backup-operator#325]
when run the restore cluster backup showing this error
[root@api.acm-br.cp.fyre.ibm.com ~]# oc describe Restore.cluster.open-cluster-management.io -n open-cluster-management-backup 
Name:         restore-acm
Namespace:    open-cluster-management-backup
Labels:       <none>
Annotations:  <none>
API Version:  cluster.open-cluster-management.io/v1beta1
Kind:         Restore
Metadata:
  Creation Timestamp:  2022-10-06T14:22:08Z
  Generation:          4
  Managed Fields:
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:cleanupBeforeRestore:
        f:veleroCredentialsBackupName:
        f:veleroManagedClustersBackupName:
        f:veleroResourcesBackupName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-06T14:22:08Z
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:lastMessage:
        f:phase:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-10-06T14:22:08Z
  Resource Version:  5398419
  UID:               2891e9f8-b207-4323-b574-656c3f1174ad
Spec:
  Cleanup Before Restore:               CleanupAll
  Velero Credentials Backup Name:       acm-credentials-cluster-schedule-20221006140010
  Velero Managed Clusters Backup Name:  acm-managed-clusters-schedule-20221006140010
  Velero Resources Backup Name:         acm-resources-schedule-20221006140010
Status:
  Last Message:  This resource is ignored because BackupSchedule resource open-cluster-management-backup is currently active, before creating another resource verify that any active resources are removed.
  Phase:         FinishedWithErrors
Events:          <none>

Name:         restore-acm-passive-activate
Namespace:    open-cluster-management-backup
Labels:       <none>
Annotations:  <none>
API Version:  cluster.open-cluster-management.io/v1beta1
Kind:         Restore
Metadata:
  Creation Timestamp:  2022-10-07T05:23:10Z
  Generation:          1
  Managed Fields:
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:cleanupBeforeRestore:
        f:veleroCredentialsBackupName:
        f:veleroManagedClustersBackupName:
        f:veleroResourcesBackupName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-07T05:23:10Z
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:lastMessage:
        f:phase:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-10-07T05:23:10Z
  Resource Version:  7986795
  UID:               c3283e4b-27ff-45a8-973a-86e0034659f5
Spec:
  Cleanup Before Restore:               CleanupRestored
  Velero Credentials Backup Name:       skip
  Velero Managed Clusters Backup Name:  acm-managed-clusters-schedule-20221006140010
  Velero Resources Backup Name:         skip
Status:
  Last Message:  This resource is ignored because BackupSchedule resource open-cluster-management-backup is currently active, before creating another resource verify that any active resources are removed.
  Phase:         FinishedWithErrors
Events:          <none>
[root@api.acm-br.cp.fyre.ibm.com ~]#

**Comment by birsanv** [comment]
@irshadstars from the error message I understand you have a `BackupSchedule.cluster.open-cluster-management.io` created on the same hub where you are trying to run the Restore operation, and this BackupSchedule is still creating backups.

_This resource is ignored because BackupSchedule resource open-cluster-management-backup is currently active, before creating another resource verify that any active resources are removed._

You are blocked from restoring data on the hub because of this potential collision in actions 
You should not have any backup schedule active and creating backups when you are running a Restore operation. 

Check that you have a BackupSchedule running

`oc get BackupShedule -A`

Once you find one delete it then try to run the restore again

**Comment by irshadstars** [comment]
@birsanv I have create different  hub now .now facing different error 
[root@api.rhacm27.cp.fyre.ibm.com ~]# oc get backup -n open-cluster-management-backup
NAME                                              AGE
acm-credentials-cluster-schedule-20221006140010   3h22m
acm-credentials-cluster-schedule-20221006160011   3h21m
acm-credentials-cluster-schedule-20221006180011   3h22m
acm-credentials-cluster-schedule-20221006200011   3h21m
acm-credentials-cluster-schedule-20221006220011   3h22m
acm-credentials-cluster-schedule-20221007000011   3h21m
acm-credentials-cluster-schedule-20221007020011   3h22m
acm-credentials-cluster-schedule-20221007040011   3h22m
acm-credentials-cluster-schedule-20221007060011   3h21m
acm-credentials-cluster-schedule-20221007080011   3h21m
acm-credentials-cluster-schedule-20221007100011   3h22m
acm-credentials-cluster-schedule-20221007120012   87m
acm-credentials-hive-schedule-20221006140010      3h21m
acm-credentials-hive-schedule-20221006160010      3h21m
acm-credentials-hive-schedule-20221006180011      3h22m
acm-credentials-hive-schedule-20221006200011      3h22m
acm-credentials-hive-schedule-20221006220011      3h22m
acm-credentials-hive-schedule-20221007000011      3h22m
acm-credentials-hive-schedule-20221007020011      3h22m
acm-credentials-hive-schedule-20221007040011      3h21m
acm-credentials-hive-schedule-20221007060011      3h22m
acm-credentials-hive-schedule-20221007080011      3h22m
acm-credentials-hive-schedule-20221007100011      3h21m
acm-credentials-hive-schedule-20221007120012      86m
acm-credentials-schedule-20221006140010           3h22m
acm-credentials-schedule-20221006160011           3h22m
acm-credentials-schedule-20221006180011           3h22m
acm-credentials-schedule-20221006200011           3h22m
acm-credentials-schedule-20221006220011           3h22m
acm-credentials-schedule-20221007000011           3h22m
acm-credentials-schedule-20221007020011           3h22m
acm-credentials-schedule-20221007040011           3h22m
acm-credentials-schedule-20221007060011           3h22m
acm-credentials-schedule-20221007080011           3h22m
acm-credentials-schedule-20221007100011           3h21m
acm-credentials-schedule-20221007120012           88m
acm-managed-clusters-schedule-20221006140010      3h22m
acm-managed-clusters-schedule-20221006160010      3h21m
acm-managed-clusters-schedule-20221006180011      3h21m
acm-managed-clusters-schedule-20221006200011      3h22m
acm-managed-clusters-schedule-20221006220011      3h22m
acm-managed-clusters-schedule-20221007000011      3h22m
acm-managed-clusters-schedule-20221007020011      3h22m
acm-managed-clusters-schedule-20221007040011      3h21m
acm-managed-clusters-schedule-20221007060011      3h22m
acm-managed-clusters-schedule-20221007080011      3h21m
acm-managed-clusters-schedule-20221007100011      3h22m
acm-managed-clusters-schedule-20221007120012      85m
acm-resources-generic-schedule-20221006140010     3h22m
acm-resources-generic-schedule-20221006160010     3h21m
acm-resources-generic-schedule-20221006180011     3h21m
acm-resources-generic-schedule-20221006200011     3h22m
acm-resources-generic-schedule-20221006220011     3h21m
acm-resources-generic-schedule-20221007000011     3h21m
acm-resources-generic-schedule-20221007020011     3h21m
acm-resources-generic-schedule-20221007040011     3h21m
acm-resources-generic-schedule-20221007060011     3h21m
acm-resources-generic-schedule-20221007080011     3h21m
acm-resources-generic-schedule-20221007100011     3h22m
acm-resources-generic-schedule-20221007120012     83m
acm-resources-schedule-20221006140010             3h22m
acm-resources-schedule-20221006160011             3h22m
acm-resources-schedule-20221006180011             3h22m
acm-resources-schedule-20221006200011             3h22m
acm-resources-schedule-20221006220011             3h22m
acm-resources-schedule-20221007000011             3h22m
acm-resources-schedule-20221007020011             3h21m
acm-resources-schedule-20221007040011             3h22m
acm-resources-schedule-20221007060011             3h22m
acm-resources-schedule-20221007080011             3h22m
acm-resources-schedule-20221007100012             3h22m
acm-resources-schedule-20221007120012             82m
acm-validation-policy-schedule-20221007120012     81m
[root@api.rhacm27.cp.fyre.ibm.com ~]# 
[root@api.rhacm27.cp.fyre.ibm.com ~]# oc get  Restore.cluster.open-cluster-management.io -n open-cluster-management-backup restore-acm
NAME          PHASE                MESSAGE
restore-acm   FinishedWithErrors   Velero restores have run to completion but encountered 1+ errors
[root@api.rhacm27.cp.fyre.ibm.com ~]# 
[root@api.rhacm27.cp.fyre.ibm.com ~]# oc describe Restore.cluster.open-cluster-management.io -n open-cluster-management-backup restore-acm
Name:         restore-acm
Namespace:    open-cluster-management-backup
Labels:       <none>
Annotations:  <none>
API Version:  cluster.open-cluster-management.io/v1beta1
Kind:         Restore
Metadata:
  Creation Timestamp:  2022-10-07T13:18:37Z
  Generation:          1
  Managed Fields:
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:cleanupBeforeRestore:
        f:veleroCredentialsBackupName:
        f:veleroManagedClustersBackupName:
        f:veleroResourcesBackupName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-07T13:18:37Z
    API Version:  cluster.open-cluster-management.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:lastMessage:
        f:phase:
        f:veleroCredentialsRestoreName:
        f:veleroManagedClustersRestoreName:
        f:veleroResourcesRestoreName:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-10-07T13:18:57Z
  Resource Version:  10398526
  UID:               7da5451c-bb3a-49f8-b464-ac29029b51a4
Spec:
  Cleanup Before Restore:               CleanupRestored
  Velero Credentials Backup Name:       acm-credentials-schedule-20221007120012
  Velero Managed Clusters Backup Name:  acm-managed-clusters-schedule-20221007120012
  Velero Resources Backup Name:         acm-resources-schedule-20221007120012
Status:
  Last Message:                          Velero restores have run to completion but encountered 1+ errors
  Phase:                                 FinishedWithErrors
  Velero Credentials Restore Name:       restore-acm-acm-credentials-schedule-20221007120012
  Velero Managed Clusters Restore Name:  restore-acm-acm-managed-clusters-schedule-20221007120012
  Velero Resources Restore Name:         restore-acm-acm-resources-schedule-20221007120012
Events:
  Type    Reason                   Age    From                Message
  ----    ------                   ----   ----                -------
  Normal  Prepare to restore:      6m24s  Restore controller  Cleaning up resources for backup acm-credentials-cluster-schedule-20221007120012
  Normal  Prepare to restore:      6m24s  Restore controller  Cleaning up resources for backup acm-credentials-schedule-20221007120012
  Normal  Prepare to restore:      6m24s  Restore controller  Cleaning up resources for backup acm-resources-generic-schedule-20221007120012
  Normal  Prepare to restore:      6m7s   Restore controller  Cleaning up resources for backup acm-resources-schedule-20221007120012
  Normal  Prepare to restore:      6m4s   Restore controller  Cleaning up resources for backup acm-credentials-hive-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-resources-generic-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-resources-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-managed-clusters-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-credentials-hive-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-credentials-cluster-schedule-20221007120012
  Normal  Velero restore created:  6m4s   Restore controller  restore-acm-acm-credentials-schedule-20221007120012

**Comment by birsanv** [comment]
@irshadstars 

So the initial issue was solved, you have no BackupSchedule active and as a result I see you can run the Restore

The second issue you are reporting refers to the status of the Restore operation , showing 

```
Last Message: Velero restores have run to completion but encountered 1+ errors
Phase: FinishedWithErrors
```
As documented here, this could mean that one of the backups had no data, which is not really an issue; but you have to investigate that by looking at the velero `Restore` results and checking the logs for the velero `Restore` showing and error status
https://github.com/stolostron/cluster-backup-operator#restore-a-backup 

_Velero sets a PartiallyFailed status for a velero restore resource if the backup restored had no resources. This means that a restore.cluster.open-cluster-management.io resource could be in PartiallyFailed status if any of the restore.velero.io resources created did not restore any resources because the corresponding backup was empty._

A few screen caps showing how to look for that log

<img width="1068" alt="Screen Shot 2022-10-07 at 9 54 00 AM" src="https://user-images.githubusercontent.com/43010150/194572174-c2c1fb74-3a40-4e05-ab86-c27bbc247bbd.png">
<img width="1080" alt="Screen Shot 2022-10-07 at 9 54 24 AM" src="https://user-images.githubusercontent.com/43010150/194572177-b67b1207-e105-4d67-b331-246923962301.png">
<img width="597" alt="Screen Shot 2022-10-07 at 9 54 59 AM" src="https://user-images.githubusercontent.com/43010150/194572180-c92391cd-ded4-4f6a-a287-1de837a825d4.png">
<img width="740" alt="Screen Shot 2022-10-07 at 10 01 38 AM" src="https://user-images.githubusercontent.com/43010150/194572181-92ce7909-7c32-4d84-b092-99bbb8cee909.png">
<img width="650" alt="Screen Shot 2022-10-07 at 10 02 05 AM" src="https://user-images.githubusercontent.com/43010150/194572184-9731f971-cdb0-410c-a971-f66a34d79d43.png">
